"""
/***************************************************************************
 console
                                 A QGIS plugin
 This is an adaption of the SylvaRoad app for in qgis uses
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-03-05
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Cosylval
        email                : yoann.zenner@viacesi.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.core import QgsMessageLog, Qgis
from qgis.PyQt.QtCore import QCoreApplication

#################################################
#.______   .______   __  .__   __. .___________.#
#|   _  \  |   _  \ |  | |  \ |  | |           |#
#|  |_)  | |  |_)  ||  | |   \|  | `---|  |----`#
#|   ___/  |      / |  | |  . `  |     |  |     #
#|  |      |  |\  \-|  | |  |\   |     |  |     #
#| _|      | _| `.__|__| |__| \__|     |__|     #
#################################################


# Fonctions qui affiche un message d'erreur dans la console
def console_warning(message):

    """ 
    Log a warning message to the console.

    This function logs a warning message to the QGIS console using the specified message.

    Args:
    - message (str): The warning message to be logged.

    Raises:
    - None

    Returns:
    - None
    """
    message = str(message)
    QgsMessageLog.logMessage(message,'SylvaRoaD',Qgis.Warning)

# Fonctions qui affiche un message d'information dans la console
def console_info(message):

    """ 
    Log an informational message to the console.

    This function logs an informational message to the QGIS console using the specified message.

    Args:
    - message (str): The informational message to be logged.

    Raises:
    - None

    Returns:
    - None
    """
    message = str(message)
    QgsMessageLog.logMessage(message,'SylvaRoaD',Qgis.Info)


def printor (number, arg = "" , arg2 = "", arg3 = ""):
    
    """ Description
    :type number:
    :param number:

    :type arg:
    :param arg:

    :type arg2:
    :param arg2:

    :type arg3:
    :param arg3:

    :raises:

    :rtype:
    """
    if number == 1:
        ver = "0.2"
        console_info(QCoreApplication.translate("MainWindow","SylvaRoaD - Version ")+ver)
        console_info(QCoreApplication.translate("MainWindow","  Verification des donnees spatiales"))
    elif number == 2:
        console_info(str(arg))
    elif number == 3:
        console_info(QCoreApplication.translate("MainWindow","  Chargement des donnees"))
    elif number == 4:
        console_info(QCoreApplication.translate("MainWindow","  Initialisation du traitement"))
    elif number == 5:
        console_info(QCoreApplication.translate("MainWindow","  Tous les tronçons ont été traités"))
    elif number == 6:
        console_info(QCoreApplication.translate("MainWindow","    Segment ")+str(arg)+QCoreApplication.translate("MainWindow"," - Progression %d") % arg2 + arg3)
    elif number == 7:
        console_info(QCoreApplication.translate("MainWindow","     - Impossible d'atteindre le Point de passage ID_POINT ")+str(arg))
    elif number == 8:
        console_info(QCoreApplication.translate("MainWindow","     - Point de passage ID_POINT ")+str(arg)+QCoreApplication.translate("MainWindow"," atteind")) 
    elif number == 9:
        console_info(QCoreApplication.translate("MainWindow","  Traitement du tronçon n°")+str(arg))
    elif number == 10:
        console_warning(QCoreApplication.translate("MainWindow","SylvaRoaD Launching..."))
    elif number == 11:
        console_warning(QCoreApplication.translate("MainWindow","SylvaRoaD finished"))

